# Sensor Calculations

<img src="sensorcalculation.png" alt="drawing" width="400"/>


- Circular agent at position $(a,b)$ with a radius of 0.1 m   
- It has 4 sensors measuring the distance in up,down,left,right directions  
- Sensors can measure up to a limited distance (say 1m)  
- Square walls with length 1 m  

How can we calculate the sensor measurements?

In [5]:
# import random
import numpy as np
import pprint

### Helper Functions

In [169]:
def getline(wall_position,wall_length):
    # line order: left,right,down,up
    # line format [x,y] as either fixed x or fixed y
    line1 = np.array([wall_position[0]-wall_length/2,None],dtype='double')
    line2 = np.array([wall_position[0]+wall_length/2,None],dtype='double')
    line3 = np.array([None,wall_position[1]-wall_length/2],dtype='double')
    line4 = np.array([None,wall_position[1]+wall_length/2],dtype='double')
    
    return([line1,line2,line3,line4])


def getsensormeasurements_(wall_position, wall_length, agent_position, agent_radius, max_sensor_dist):
    '''
    Returns an array of sensor measurements (distances) in form of: [left,right,down,up]
    '''
    measurements = [max_sensor_dist]*4
    #calculations start
    [line1,line2,line3,line4] = getline(wall_position,wall_length)
    
    #left sensor
    if (wall_position[1] - agent_position[1])**2 < (wall_length/2)**2:
        dist1 = agent_position[0] - line2[0]
        if dist1 > 0:
            if dist1 < max_sensor_dist:
                measurements[0] = dist1
    
    #right sensor
    if (wall_position[1] - agent_position[1])**2 < (wall_length/2)**2:
        dist2 = line1[0] - agent_position[0]
        if dist2 > 0:
            if dist2 < max_sensor_dist:
                measurements[1] = dist2
    
    #down sensor
    if (wall_position[0] - agent_position[0])**2 < (wall_length/2)**2:
        dist3 = agent_position[1] - line4[1]
        if dist3 > 0:
            if dist3 < max_sensor_dist:
                measurements[2] = dist3
    
    #up sensor
    if (wall_position[0] - agent_position[0])**2 < (wall_length/2)**2:
        dist4 = line3[1] - agent_position[1]
        if dist4 > 0:
            if dist4 < max_sensor_dist:
                measurements[3] = dist4

    #calculations end
    return measurements

def getsensormeasurements_2(other_agent_pos, agent_position, agent_radius, max_sensor_dist):
    '''
    Returns an array of sensor measurements (distances) in form of: [left,right,down,up]
    Looks for other agents
    '''
    measurements = [max_sensor_dist]*4
    
    # left sensor
    if (other_agent_pos[1] - agent_position[1])**2 < (agent_radius)**2:
        c =  agent_position - other_agent_pos
        b = c[0]
        a = c[1]
        dist1 = b - math.sqrt(agent_radius**2 - a**2) 
        if dist1 >= 0:
            if dist1 < max_sensor_dist:
                measurements[0] = dist1
                
    # right sensor
    if (other_agent_pos[1] - agent_position[1])**2 < (agent_radius)**2:
        c =  other_agent_pos - agent_position
        b = c[0]
        a = c[1]
        dist2 = b - math.sqrt(agent_radius**2 - a**2) 
        if dist2 >= 0:
            if dist2 < max_sensor_dist:
                measurements[1] = dist2  
                
    # down sensor
    if (other_agent_pos[0] - agent_position[0])**2 < (agent_radius)**2:
        c =  agent_position - other_agent_pos
        b = c[1]
        a = c[0]
        dist3 = b - math.sqrt(agent_radius**2 - a**2) 
        if dist3 >= 0:
            if dist3 < max_sensor_dist:
                measurements[2] = dist3
    
    # up sensor
    if (other_agent_pos[0] - agent_position[0])**2 < (agent_radius)**2:
        c =  other_agent_pos - agent_position
        b = c[1]
        a = c[0]
        dist4 = b - math.sqrt(agent_radius**2 - a**2) 
        if dist4 >= 0:
            if dist4 < max_sensor_dist:
                measurements[3] = dist4   
                
    return measurements

In [196]:
def getsensormeasurements(other_agent_positions,wall_positions,wall_length,agent_position, agent_radius, max_sensor_dist):
    '''
    Returns an array of sensor measurements (distances) in form of: [left,right,down,up]
    '''
    measurements = [max_sensor_dist]*4
    #calculations start
    
    meas1 = np.array([getsensormeasurements_(w_pos,wall_length,agent_position,agent_radius,max_sensor_dist) for w_pos in wall_positions]) 
    meas1_ = meas1.min(axis=0)
    
    meas2 = np.array([getsensormeasurements_2(o_a_pos, agent_position, agent_radius, max_sensor_dist) for o_a_pos in other_agent_positions])
    meas2_ = meas2.min(axis=0)
    
  
    pprint.pprint(meas1)
    print('-'*30)
    pprint.pprint(meas2)
    

    #calculations end
    return np.vstack((meas1_,meas2_)).min(axis=0)

In [201]:
other_agent_positions = [np.array([-0.3,0]),np.array([0.2,0]),np.array([0,1]),np.array([0,0])]
wall_positions    = [np.array([0,3]),np.array([0,2]),np.array([0,1]),np.array([0,0]),np.array([1,0]),np.array([2,0]),np.array([3,0])]
wall_length       = 1
agent_position    = np.array([0,0])
other_agent_pos   = np.array([0.,0])
agent_radius      = 0.1
max_sensor_dist   = 1

In [202]:
getsensormeasurements_2(other_agent_pos, agent_position, agent_radius, max_sensor_dist)

[1, 1, 1, 1]

In [203]:
getsensormeasurements_(other_agent_pos, wall_length, agent_position, agent_radius, max_sensor_dist)

[1, 1, 1, 1]

In [204]:
getsensormeasurements(other_agent_positions,wall_positions,wall_length,agent_position, agent_radius, max_sensor_dist)

array([[1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0.5],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. ]])
------------------------------
array([[0.2, 1. , 1. , 1. ],
       [1. , 0.1, 1. , 1. ],
       [1. , 1. , 1. , 0.9],
       [1. , 1. , 1. , 1. ]])


array([0.2, 0.1, 1. , 0.5])